heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://vote
    - http://result
# - type: icmp
#   schedule: '@every 5s'
#   hosts:
#     - elasticsearch
#     - kibana

# processors:
# - add_cloud_metadata: ~


cloud.id: "${ES_CLOUD_ID}"
cloud.auth: "${ES_USERNAME}:${ES_PASSWORD}"


# output.elasticsearch:
#   hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#   username: '${ELASTICSEARCH_USERNAME:}'
#   password: '${ELASTICSEARCH_PASSWORD:}'