filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      labels.dedot: true
      templates:
        - condition:
            contains:
              docker.container.image: db
          config:
            - module: postgresql
              log:
                input:
                  type: docker
                  containers.ids:
                    - "${data.docker.container.id}"
        - condition:
            contains:
              docker.container.image: redis
          config:
            - module: redis
              log:
                enabled: true
                input:
                  type: docker
                  containers.ids:
                    - "${data.docker.container.id}"
              slowlog:
                enabled: true
                var.hosts: ["${data.host}:${data.port}"]

processors:
- add_cloud_metadata: ~

setup.dashboards.enabled: true

cloud.id: "${ES_CLOUD_ID}"
cloud.auth: "${ES_USERNAME}:${ES_PASSWORD}"


#output.elasticsearch:
#   hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#   username: '${ELASTICSEARCH_USERNAME:}'
#   password: '${ELASTICSEARCH_PASSWORD:}'