metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      labels.dedot: true
      templates:
        - condition:
            contains:
              docker.container.image: redis
          config:
            - module: redis
              metricsets: ["info", "keyspace"]
              hosts: "${data.host}:${data.port}"
        - condition:
            contains:
              docker.container.image: db
          config:
            - module: postgresql
              metricsets: [database, bgwriter, activity]
              period: 10s
              hosts: ["postgres://${data.host}:${data.port}?sslmode=disable"]
              username: ${PG_USER}
              password: ${PG_PASSWORD}


metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true
  

processors:
  - add_cloud_metadata: ~


cloud.id: "${ES_CLOUD_ID}"
cloud.auth: "${ES_USERNAME}:${ES_PASSWORD}"

# output.elasticsearch:
#   hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#   username: '${ELASTICSEARCH_USERNAME:}'
#   password: '${ELASTICSEARCH_PASSWORD:}'

## dasboard setup
setup.dashboards.enabled: true